# Default values for deploying Grafana in mainflux
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# images
grafanaImage: "grafana/grafana:5.1.3"

namespace: "default"

grafana:
  name: "mainflux-grafana"
  port: 3000

replicas: 1

pullPolicy: Always

serviceType: LoadBalancer
